language: r
sudo: required

warnings_are_errors: true

r_github_packages:
  - jimhester/covr

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always