---
title: "Using ethnicolor"
author: "Gaurav Sood"
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{Illustrating how to use ethnicolor}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

### ethnicolor: Impute Race and Ethnicity Based on Name


#### Install and Load the package

The latest development version of the package will always be on GitHub. To install the package from GitHub and to load the installed package:

```{r, eval=FALSE, install}
#library(devtools)
install_github("soodoku/ethnicolor")
```

To install the package from CRAN, type in: 

```{r, eval=FALSE, cran_install}
install.packages("ethnicolor")
```

Next, load the package:

```{r, eval=FALSE, load_pkg}
library(ethnicolor)
```

#### Census Data

To get category of the content from the Census last name data:

```{r, eval=FALSE, base_census}
cs_surname("Smith")[,1:10]
```

```
##
##   name cs2000_rank cs2000_count cs2000_prop100k cs2000_cum_prop100k cs2000_pctwhite cs2000_pctblack cs2000_pctapi cs2000_pctaian cs2000_pct2prace
## 1 smith           1      2376206          880.85              880.85           73.35           22.22           0.4           0.85             1.6
```

